/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.reimbursement;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;

public class App {

    public static void main(String[] args) throws ParseException {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH);
        String dateInString = "7-Jun-2020";
        String dateEndInString = "10-Jun-2020";
        Date x = new Date();
        Date y = formatter.parse(dateInString);
        Date startDate = formatter.parse(dateInString);
        Date endDate = formatter.parse(dateEndInString);

        Day day = new Day(x, CityType.LOW_COST);
        Day day2 = new Day(x, CityType.HIGH_COST);
        Day day3 = new Day(y, CityType.LOW_COST);

        HashMap<Date, Day> days = new HashMap<>();

        addDayToList(day, days);
        addDayToList(day2, days);
        addDayToList(day3, days);

        days.values().stream().forEach(singleDay -> {
            System.out.println("Day Added: " + singleDay.getDate());
        });

        Project project = new Project(startDate, endDate, CityType.LOW_COST);

    }

    public static void addDayToList(Day day, HashMap<Date, Day> days) {
        if (days.containsKey(day.getDate())) {
            Day existingDay = days.get(day.getDate());
            if (CityType.LOW_COST.equals(existingDay.getType())) {
                if (CityType.HIGH_COST.equals(day.getType())) {
                    days.remove(day.getDate());
                    days.put(day.getDate(), day);
                }
            }
        } else {
            days.put(day.getDate(), day);
        }
    }

}
